import Head from 'next/head'
import Login from '../pages/login.js'
import styles from '../styles/Home.module.css'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <header className={styles.head}>
       <div className={styles.left}>ALIGARH MUSLIM UNIVERSITY</div>
       <div className={styles.right}><ul className={styles.nav}>
        <li><a href="#">ABOUT</a></li>
        <li><a href="#">USEFUL DOWNLOADS</a></li>
        <li><a href="#">NOTICES</a></li>
        <li><a href="#">CONTACT</a></li>
        </ul>
       </div>
      </header>
      <div className={styles.mid}>
        <div className={styles.logo}>
          <img src="public/img/amulogo.png" alt="logo"></img>
          <div>ALIGARH MUSLIM UNIVERSITY</div>
          </div>
        <h1>NBA Record Management System</h1>
        <div className={styles.detail}>NBA Record Management System is a web application for maintaining and automating the record of all courses that are taught in the class throughout the program. This software analyzes the course outcomes, program outcomes, course specific outcomes and marks gained in each outcome based section. It also analyzes the achievements of the students in their graduation and after graduation in this program on the basis of research papers published, internships, projects and placement.</div>
      </div>
      <div className={styles.middle}>
        <ul className={styles.navbar}>
          <li><a href="#">Student</a></li>
          <li><a href="#">Teacher</a></li>
          <li><a href="#">Admin</a></li>
          <li><a href="#">Help Desk</a></li>
          
          
        </ul>

      </div>
      <Login/>
    
    
  
  </div>
  )
}
